{
  "cve_id": "CVE-2024-52312",
  "github_data": {
    "repository": "data-dot-all/dataall",
    "fix_commit": null,
    "related_commits": [],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 5.4,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:L",
    "cwe_id": "CWE-863",
    "description": "Due to inconsistent authorization permissions, data.all may allow an external actor with an authenticated account to perform restricted operations against DataSets and Environments.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2024-11-09T01:15:04.753",
    "last_modified": "2024-11-12T13:56:54.483",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://aws.amazon.com/security/security-bulletins/AWS-2024-013",
      "source": "ff89ba41-3aa1-4d27-914a-91399e9639e5",
      "tags": []
    },
    {
      "url": "https://github.com/data-dot-all/dataall/security/advisories/GHSA-676j-g6g5-chj9",
      "source": "ff89ba41-3aa1-4d27-914a-91399e9639e5",
      "tags": []
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:09:29.273155",
    "processing_status": "raw"
  }
}