{
  "cve_id": "CVE-2022-31313",
  "github_data": {
    "repository": "rakeshrkz7/as_api_res",
    "fix_commit": null,
    "related_commits": [],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 9.8,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "cwe_id": null,
    "description": "api-res-py package in PyPI 0.1 is vulnerable to a code execution backdoor in the request package.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2022-06-08T20:15:08.087",
    "last_modified": "2024-11-21T07:04:19.657",
    "fix_date": null
  },
  "references": [
    {
      "url": "http://pypi.doubanio.com/simple/request",
      "source": "cve@mitre.org",
      "tags": [
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/rakeshrkz7/as_api_res/issues/1",
      "source": "cve@mitre.org",
      "tags": [
        "Broken Link"
      ]
    },
    {
      "url": "https://pypi.org/project/api-res-py/",
      "source": "cve@mitre.org",
      "tags": [
        "Third Party Advisory"
      ]
    },
    {
      "url": "http://pypi.doubanio.com/simple/request",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/rakeshrkz7/as_api_res/issues/1",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Broken Link"
      ]
    },
    {
      "url": "https://pypi.org/project/api-res-py/",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Third Party Advisory"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:03:09.419246",
    "processing_status": "raw"
  }
}