{
  "cve_id": "CVE-2015-5159",
  "github_data": {
    "repository": "latchset/kdcproxy",
    "fix_commit": "f274aa6787cb8b3ec1cc12c440a56665b7231882",
    "related_commits": [
      "f274aa6787cb8b3ec1cc12c440a56665b7231882",
      "f274aa6787cb8b3ec1cc12c440a56665b7231882"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": null,
    "cvss_vector": null,
    "cwe_id": "CWE-20",
    "description": "python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request.",
    "attack_vector": null,
    "attack_complexity": null
  },
  "temporal_data": {
    "published_date": "2018-10-30T18:29:00.207",
    "last_modified": "2024-11-21T02:32:28.250",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200",
      "source": "secalert@redhat.com",
      "tags": [
        "Issue Tracking",
        "Mitigation",
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882",
      "source": "secalert@redhat.com",
      "tags": [
        "Patch",
        "Vendor Advisory"
      ]
    },
    {
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Issue Tracking",
        "Mitigation",
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch",
        "Vendor Advisory"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T22:59:38.541201",
    "processing_status": "raw"
  }
}