{
  "cve_id": "CVE-2021-27213",
  "github_data": {
    "repository": "cvandeplas/pystemon",
    "fix_commit": "dbeb87afefdb63de2f4cff69b6f10c5965d14b54",
    "related_commits": [
      "dbeb87afefdb63de2f4cff69b6f10c5965d14b54",
      "dbeb87afefdb63de2f4cff69b6f10c5965d14b54"
    ],
    "patch_url": null
  },
  "vulnerability_details": {
    "cvss_score": 9.8,
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
    "cwe_id": "CWE-502",
    "description": "config.py in pystemon before 2021-02-13 allows code execution via YAML deserialization because SafeLoader and safe_load are not used.",
    "attack_vector": "NETWORK",
    "attack_complexity": "LOW"
  },
  "temporal_data": {
    "published_date": "2021-02-14T04:15:12.837",
    "last_modified": "2024-11-21T05:57:36.437",
    "fix_date": null
  },
  "references": [
    {
      "url": "https://github.com/cvandeplas/pystemon/commit/dbeb87afefdb63de2f4cff69b6f10c5965d14b54",
      "source": "cve@mitre.org",
      "tags": [
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://www.huntr.dev/bounties/1-other-pystemon/",
      "source": "cve@mitre.org",
      "tags": [
        "Exploit",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://github.com/cvandeplas/pystemon/commit/dbeb87afefdb63de2f4cff69b6f10c5965d14b54",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Patch",
        "Third Party Advisory"
      ]
    },
    {
      "url": "https://www.huntr.dev/bounties/1-other-pystemon/",
      "source": "af854a3a-2127-422b-91ae-364da2661108",
      "tags": [
        "Exploit",
        "Third Party Advisory"
      ]
    }
  ],
  "collection_metadata": {
    "collected_at": "2025-01-11T23:01:16.785601",
    "processing_status": "raw"
  }
}